config/routes.rb
Rails.application.routes.draw do

  resources :cb_relationships
  resources :cb_people
  resources :cb_offices
  resources :cb_objects
  resources :cb_milestones
  resources :cb_ipos
  resources :cb_investments
  resources :cb_funds
  resources :cb_funding_rounds
  resources :cb_degrees
  resources :cb_acquisitions
  root to: 'quantic#index'
  get 'quantic/about'

  devise_for :users

  authenticated :user do
    get 'quantic/browse' => 'cb_objects#index'
    get 'quantic/search' => 'cb_objects#search'
  end
  
  

end

app/models/cb_acquisition.rb
class CbAcquisition < ApplicationRecord
  belongs_to :acquisition
  belongs_to :acquiring_object
  belongs_to :acquired_object
end

app/models/cb_degree.rb
class CbDegree < ApplicationRecord
  belongs_to :object
end

app/models/cb_fund.rb
class CbFund < ApplicationRecord
  belongs_to :fund
  belongs_to :object
end

app/models/cb_funding_round.rb
class CbFundingRound < ApplicationRecord
  belongs_to :funding_round
  belongs_to :object
end

app/models/cb_investment.rb
class CbInvestment < ApplicationRecord
  belongs_to :funding_round
  belongs_to :funded_object
  belongs_to :investor_object
end

app/models/cb_ipo.rb
class CbIpo < ApplicationRecord
  belongs_to :ipo
  belongs_to :object
end

app/models/cb_milestone.rb
class CbMilestone < ApplicationRecord
  belongs_to :object
end

app/models/cb_object.rb
class CbObject < ActiveRecord::Base
#include Elasticsearch::Model
#include Elasticsearch::Model::CallBacks
  belongs_to :entity
  belongs_to :parent

  def self.search(search)
	  if search
		  name = name.find_by(name: search)
		if cb_object
			self.where(cb_objects_id: cb_object)
		else
		 cb_object.all
	 	end
       	else
	cb_object.all
	end
  	end

  def next
    self.class.where("id > ?", id).first
  end

  def previous
    self.class.where("id < ?", id).last
  end

end

app/models/cb_office.rb
class CbOffice < ApplicationRecord
  belongs_to :object
  belongs_to :office
end

app/models/cb_person.rb
class CbPerson < ApplicationRecord
  belongs_to :object
end

app/models/cb_relationship.rb
class CbRelationship < ApplicationRecord
  belongs_to :relationship
  belongs_to :person_object
  belongs_to :relationship_object
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cb_acquisitions_controller.rb
class CbAcquisitionsController < ApplicationController
  before_action :set_cb_acquisition, only: [:show, :edit, :update, :destroy]

  # GET /cb_acquisitions
  # GET /cb_acquisitions.json
  def index
    @cb_acquisitions = CbAcquisition.all
  end

  # GET /cb_acquisitions/1
  # GET /cb_acquisitions/1.json
  def show
  end

  # GET /cb_acquisitions/new
  def new
    @cb_acquisition = CbAcquisition.new
  end

  # GET /cb_acquisitions/1/edit
  def edit
  end

  # POST /cb_acquisitions
  # POST /cb_acquisitions.json
  def create
    @cb_acquisition = CbAcquisition.new(cb_acquisition_params)

    respond_to do |format|
      if @cb_acquisition.save
        format.html { redirect_to @cb_acquisition, notice: 'Cb acquisition was successfully created.' }
        format.json { render :show, status: :created, location: @cb_acquisition }
      else
        format.html { render :new }
        format.json { render json: @cb_acquisition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cb_acquisitions/1
  # PATCH/PUT /cb_acquisitions/1.json
  def update
    respond_to do |format|
      if @cb_acquisition.update(cb_acquisition_params)
        format.html { redirect_to @cb_acquisition, notice: 'Cb acquisition was successfully updated.' }
        format.json { render :show, status: :ok, location: @cb_acquisition }
      else
        format.html { render :edit }
        format.json { render json: @cb_acquisition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cb_acquisitions/1
  # DELETE /cb_acquisitions/1.json
  def destroy
    @cb_acquisition.destroy
    respond_to do |format|
      format.html { redirect_to cb_acquisitions_url, notice: 'Cb acquisition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cb_acquisition
      @cb_acquisition = CbAcquisition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cb_acquisition_params
      params.require(:cb_acquisition).permit(:acquisition_id, :acquiring_object_id, :acquired_object_id, :term_code, :price_amount, :price_currency_code, :acquired_at, :source_url, :source_description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cb_acquisitions_helper.rb
module CbAcquisitionsHelper
end

app/helpers/cb_degrees_helper.rb
module CbDegreesHelper
end

app/helpers/cb_funds_helper.rb
module CbFundsHelper
end

app/helpers/cb_ipos_helper.rb
module CbIposHelper
end

app/helpers/cb_milestones_helper.rb
module CbMilestonesHelper
end

app/helpers/cb_objects_helper.rb
module CbObjectsHelper
end

app/helpers/cb_offices_helper.rb
module CbOfficesHelper
end

app/helpers/cb_people_helper.rb
module CbPeopleHelper
end

app/helpers/quantic_helper.rb
module QuanticHelper
    def bootstrap_version
        "4.2.1"
    end 
end

app/views/cb_acquisitions/_form.html.erb
<%= form_with(model: cb_acquisition, local: true) do |form| %>
  <% if cb_acquisition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cb_acquisition.errors.count, "error") %> prohibited this cb_acquisition from being saved:</h2>

      <ul>
      <% cb_acquisition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :acquisition_id %>
    <%= form.text_field :acquisition_id %>
  </div>

  <div class="field">
    <%= form.label :acquiring_object_id %>
    <%= form.text_field :acquiring_object_id %>
  </div>

  <div class="field">
    <%= form.label :acquired_object_id %>
    <%= form.text_field :acquired_object_id %>
  </div>

  <div class="field">
    <%= form.label :term_code %>
    <%= form.text_field :term_code %>
  </div>

  <div class="field">
    <%= form.label :price_amount %>
    <%= form.text_field :price_amount %>
  </div>

  <div class="field">
    <%= form.label :price_currency_code %>
    <%= form.text_field :price_currency_code %>
  </div>

  <div class="field">
    <%= form.label :acquired_at %>
    <%= form.date_select :acquired_at %>
  </div>

  <div class="field">
    <%= form.label :source_url %>
    <%= form.text_field :source_url %>
  </div>

  <div class="field">
    <%= form.label :source_description %>
    <%= form.text_field :source_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cb_acquisitions/edit.html.erb
<h1>Editing Cb Acquisition</h1>

<%= render 'form', cb_acquisition: @cb_acquisition %>

<%= link_to 'Show', @cb_acquisition %> |
<%= link_to 'Back', cb_acquisitions_path %>

app/views/cb_acquisitions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cb Acquisitions</h1>

<table>
  <thead>
    <tr>
      <th>Acquisition</th>
      <th>Acquiring object</th>
      <th>Acquired object</th>
      <th>Term code</th>
      <th>Price amount</th>
      <th>Price currency code</th>
      <th>Acquired at</th>
      <th>Source url</th>
      <th>Source description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cb_acquisitions.each do |cb_acquisition| %>
      <tr>
        <td><%= cb_acquisition.acquisition %></td>
        <td><%= cb_acquisition.acquiring_object %></td>
        <td><%= cb_acquisition.acquired_object %></td>
        <td><%= cb_acquisition.term_code %></td>
        <td><%= cb_acquisition.price_amount %></td>
        <td><%= cb_acquisition.price_currency_code %></td>
        <td><%= cb_acquisition.acquired_at %></td>
        <td><%= cb_acquisition.source_url %></td>
        <td><%= cb_acquisition.source_description %></td>
        <td><%= link_to 'Show', cb_acquisition %></td>
        <td><%= link_to 'Edit', edit_cb_acquisition_path(cb_acquisition) %></td>
        <td><%= link_to 'Destroy', cb_acquisition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cb Acquisition', new_cb_acquisition_path %>

app/views/cb_acquisitions/new.html.erb
<h1>New Cb Acquisition</h1>

<%= render 'form', cb_acquisition: @cb_acquisition %>

<%= link_to 'Back', cb_acquisitions_path %>

app/views/cb_acquisitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Acquisition:</strong>
  <%= @cb_acquisition.acquisition %>
</p>

<p>
  <strong>Acquiring object:</strong>
  <%= @cb_acquisition.acquiring_object %>
</p>

<p>
  <strong>Acquired object:</strong>
  <%= @cb_acquisition.acquired_object %>
</p>

<p>
  <strong>Term code:</strong>
  <%= @cb_acquisition.term_code %>
</p>

<p>
  <strong>Price amount:</strong>
  <%= @cb_acquisition.price_amount %>
</p>

<p>
  <strong>Price currency code:</strong>
  <%= @cb_acquisition.price_currency_code %>
</p>

<p>
  <strong>Acquired at:</strong>
  <%= @cb_acquisition.acquired_at %>
</p>

<p>
  <strong>Source url:</strong>
  <%= @cb_acquisition.source_url %>
</p>

<p>
  <strong>Source description:</strong>
  <%= @cb_acquisition.source_description %>
</p>

<%= link_to 'Edit', edit_cb_acquisition_path(@cb_acquisition) %> |
<%= link_to 'Back', cb_acquisitions_path %>