config/routes.rb
Rails.application.routes.draw do

  resources :cb_relationships
  resources :cb_people
  resources :cb_offices
  resources :cb_objects
  resources :cb_milestones
  resources :cb_ipos
  resources :cb_investments
  resources :cb_funds
  resources :cb_funding_rounds
  resources :cb_degrees
  resources :cb_acquisitions
  root to: 'quantic#index'
  get 'quantic/about'

  devise_for :users

  authenticated :user do
    get 'quantic/browse' => 'cb_objects#index'
    get 'quantic/search' => 'cb_objects#search'
  end
  
  

end

app/models/cb_acquisition.rb
class CbAcquisition < ApplicationRecord
  belongs_to :acquisition
  belongs_to :acquiring_object
  belongs_to :acquired_object
end

app/models/cb_degree.rb
class CbDegree < ApplicationRecord
  belongs_to :object
end

app/models/cb_fund.rb
class CbFund < ApplicationRecord
  belongs_to :fund
  belongs_to :object
end

app/models/cb_funding_round.rb
class CbFundingRound < ApplicationRecord
  belongs_to :funding_round
  belongs_to :object
end

app/models/cb_investment.rb
class CbInvestment < ApplicationRecord
  belongs_to :funding_round
  belongs_to :funded_object
  belongs_to :investor_object
end

app/models/cb_ipo.rb
class CbIpo < ApplicationRecord
  belongs_to :ipo
  belongs_to :object
end

app/models/cb_milestone.rb
class CbMilestone < ApplicationRecord
  belongs_to :object
end

app/models/cb_object.rb
class CbObject < ActiveRecord::Base
#include Elasticsearch::Model
#include Elasticsearch::Model::CallBacks
  belongs_to :entity
  belongs_to :parent

  def self.search(search)
	  if search
		  name = name.find_by(name: search)
		if cb_object
			self.where(cb_objects_id: cb_object)
		else
		 cb_object.all
	 	end
       	else
	cb_object.all
	end
  	end

  def next
    self.class.where("id > ?", id).first
  end

  def previous
    self.class.where("id < ?", id).last
  end

end

app/models/cb_office.rb
class CbOffice < ApplicationRecord
  belongs_to :object
  belongs_to :office
end

app/models/cb_person.rb
class CbPerson < ApplicationRecord
  belongs_to :object
end

app/models/cb_relationship.rb
class CbRelationship < ApplicationRecord
  belongs_to :relationship
  belongs_to :person_object
  belongs_to :relationship_object
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cb_milestones_controller.rb
class CbMilestonesController < ApplicationController
  before_action :set_cb_milestone, only: [:show, :edit, :update, :destroy]

  # GET /cb_milestones
  # GET /cb_milestones.json
  def index
    @cb_milestones = CbMilestone.all
  end

  # GET /cb_milestones/1
  # GET /cb_milestones/1.json
  def show
  end

  # GET /cb_milestones/new
  def new
    @cb_milestone = CbMilestone.new
  end

  # GET /cb_milestones/1/edit
  def edit
  end

  # POST /cb_milestones
  # POST /cb_milestones.json
  def create
    @cb_milestone = CbMilestone.new(cb_milestone_params)

    respond_to do |format|
      if @cb_milestone.save
        format.html { redirect_to @cb_milestone, notice: 'Cb milestone was successfully created.' }
        format.json { render :show, status: :created, location: @cb_milestone }
      else
        format.html { render :new }
        format.json { render json: @cb_milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cb_milestones/1
  # PATCH/PUT /cb_milestones/1.json
  def update
    respond_to do |format|
      if @cb_milestone.update(cb_milestone_params)
        format.html { redirect_to @cb_milestone, notice: 'Cb milestone was successfully updated.' }
        format.json { render :show, status: :ok, location: @cb_milestone }
      else
        format.html { render :edit }
        format.json { render json: @cb_milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cb_milestones/1
  # DELETE /cb_milestones/1.json
  def destroy
    @cb_milestone.destroy
    respond_to do |format|
      format.html { redirect_to cb_milestones_url, notice: 'Cb milestone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cb_milestone
      @cb_milestone = CbMilestone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cb_milestone_params
      params.require(:cb_milestone).permit(:object_id, :milestone_at, :milestone_code, :description, :source_url, :source_description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cb_degrees_helper.rb
module CbDegreesHelper
end

app/helpers/cb_funds_helper.rb
module CbFundsHelper
end

app/helpers/cb_investments_helper.rb
module CbInvestmentsHelper
end

app/helpers/cb_ipos_helper.rb
module CbIposHelper
end

app/helpers/cb_milestones_helper.rb
module CbMilestonesHelper
end

app/helpers/cb_objects_helper.rb
module CbObjectsHelper
end

app/helpers/cb_offices_helper.rb
module CbOfficesHelper
end

app/helpers/cb_people_helper.rb
module CbPeopleHelper
end

app/helpers/quantic_helper.rb
module QuanticHelper
    def bootstrap_version
        "4.2.1"
    end 
end

app/views/cb_milestones/_form.html.erb
<%= form_with(model: cb_milestone, local: true) do |form| %>
  <% if cb_milestone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cb_milestone.errors.count, "error") %> prohibited this cb_milestone from being saved:</h2>

      <ul>
      <% cb_milestone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :object_id %>
    <%= form.text_field :object_id %>
  </div>

  <div class="field">
    <%= form.label :milestone_at %>
    <%= form.date_select :milestone_at %>
  </div>

  <div class="field">
    <%= form.label :milestone_code %>
    <%= form.text_field :milestone_code %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :source_url %>
    <%= form.text_field :source_url %>
  </div>

  <div class="field">
    <%= form.label :source_description %>
    <%= form.text_field :source_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cb_milestones/edit.html.erb
<h1>Editing Cb Milestone</h1>

<%= render 'form', cb_milestone: @cb_milestone %>

<%= link_to 'Show', @cb_milestone %> |
<%= link_to 'Back', cb_milestones_path %>

app/views/cb_milestones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cb Milestones</h1>

<table>
  <thead>
    <tr>
      <th>Object</th>
      <th>Milestone at</th>
      <th>Milestone code</th>
      <th>Description</th>
      <th>Source url</th>
      <th>Source description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cb_milestones.each do |cb_milestone| %>
      <tr>
        <td><%= cb_milestone.object %></td>
        <td><%= cb_milestone.milestone_at %></td>
        <td><%= cb_milestone.milestone_code %></td>
        <td><%= cb_milestone.description %></td>
        <td><%= cb_milestone.source_url %></td>
        <td><%= cb_milestone.source_description %></td>
        <td><%= link_to 'Show', cb_milestone %></td>
        <td><%= link_to 'Edit', edit_cb_milestone_path(cb_milestone) %></td>
        <td><%= link_to 'Destroy', cb_milestone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cb Milestone', new_cb_milestone_path %>

app/views/cb_milestones/new.html.erb
<h1>New Cb Milestone</h1>

<%= render 'form', cb_milestone: @cb_milestone %>

<%= link_to 'Back', cb_milestones_path %>

app/views/cb_milestones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Object:</strong>
  <%= @cb_milestone.object %>
</p>

<p>
  <strong>Milestone at:</strong>
  <%= @cb_milestone.milestone_at %>
</p>

<p>
  <strong>Milestone code:</strong>
  <%= @cb_milestone.milestone_code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cb_milestone.description %>
</p>

<p>
  <strong>Source url:</strong>
  <%= @cb_milestone.source_url %>
</p>

<p>
  <strong>Source description:</strong>
  <%= @cb_milestone.source_description %>
</p>

<%= link_to 'Edit', edit_cb_milestone_path(@cb_milestone) %> |
<%= link_to 'Back', cb_milestones_path %>