config/routes.rb
Rails.application.routes.draw do

  resources :cb_relationships
  resources :cb_people
  resources :cb_offices
  resources :cb_objects
  resources :cb_milestones
  resources :cb_ipos
  resources :cb_investments
  resources :cb_funds
  resources :cb_funding_rounds
  resources :cb_degrees
  resources :cb_acquisitions
  root to: 'quantic#index'
  get 'quantic/about'

  devise_for :users

  authenticated :user do
    get 'quantic/browse' => 'cb_objects#index'
    get 'quantic/search' => 'cb_objects#search'
  end
  
  

end

app/models/cb_acquisition.rb
class CbAcquisition < ApplicationRecord
  belongs_to :acquisition
  belongs_to :acquiring_object
  belongs_to :acquired_object
end

app/models/cb_degree.rb
class CbDegree < ApplicationRecord
  belongs_to :object
end

app/models/cb_fund.rb
class CbFund < ApplicationRecord
  belongs_to :fund
  belongs_to :object
end

app/models/cb_funding_round.rb
class CbFundingRound < ApplicationRecord
  belongs_to :funding_round
  belongs_to :object
end

app/models/cb_investment.rb
class CbInvestment < ApplicationRecord
  belongs_to :funding_round
  belongs_to :funded_object
  belongs_to :investor_object
end

app/models/cb_ipo.rb
class CbIpo < ApplicationRecord
  belongs_to :ipo
  belongs_to :object
end

app/models/cb_milestone.rb
class CbMilestone < ApplicationRecord
  belongs_to :object
end

app/models/cb_object.rb
class CbObject < ActiveRecord::Base
#include Elasticsearch::Model
#include Elasticsearch::Model::CallBacks
  belongs_to :entity
  belongs_to :parent

  def self.search(search)
	  if search
		  name = name.find_by(name: search)
		if cb_object
			self.where(cb_objects_id: cb_object)
		else
		 cb_object.all
	 	end
       	else
	cb_object.all
	end
  	end

  def next
    self.class.where("id > ?", id).first
  end

  def previous
    self.class.where("id < ?", id).last
  end

end

app/models/cb_office.rb
class CbOffice < ApplicationRecord
  belongs_to :object
  belongs_to :office
end

app/models/cb_person.rb
class CbPerson < ApplicationRecord
  belongs_to :object
end

app/models/cb_relationship.rb
class CbRelationship < ApplicationRecord
  belongs_to :relationship
  belongs_to :person_object
  belongs_to :relationship_object
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cb_funds_controller.rb
class CbFundsController < ApplicationController
  before_action :set_cb_fund, only: [:show, :edit, :update, :destroy]

  # GET /cb_funds
  # GET /cb_funds.json
  def index
    @cb_funds = CbFund.all
  end

  # GET /cb_funds/1
  # GET /cb_funds/1.json
  def show
  end

  # GET /cb_funds/new
  def new
    @cb_fund = CbFund.new
  end

  # GET /cb_funds/1/edit
  def edit
  end

  # POST /cb_funds
  # POST /cb_funds.json
  def create
    @cb_fund = CbFund.new(cb_fund_params)

    respond_to do |format|
      if @cb_fund.save
        format.html { redirect_to @cb_fund, notice: 'Cb fund was successfully created.' }
        format.json { render :show, status: :created, location: @cb_fund }
      else
        format.html { render :new }
        format.json { render json: @cb_fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cb_funds/1
  # PATCH/PUT /cb_funds/1.json
  def update
    respond_to do |format|
      if @cb_fund.update(cb_fund_params)
        format.html { redirect_to @cb_fund, notice: 'Cb fund was successfully updated.' }
        format.json { render :show, status: :ok, location: @cb_fund }
      else
        format.html { render :edit }
        format.json { render json: @cb_fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cb_funds/1
  # DELETE /cb_funds/1.json
  def destroy
    @cb_fund.destroy
    respond_to do |format|
      format.html { redirect_to cb_funds_url, notice: 'Cb fund was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cb_fund
      @cb_fund = CbFund.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cb_fund_params
      params.require(:cb_fund).permit(:fund_id, :object_id, :name, :funded_at, :raised_amount, :raised_currency_code, :source_url, :source_description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cb_degrees_helper.rb
module CbDegreesHelper
end

app/helpers/cb_funds_helper.rb
module CbFundsHelper
end

app/helpers/cb_investments_helper.rb
module CbInvestmentsHelper
end

app/helpers/cb_ipos_helper.rb
module CbIposHelper
end

app/helpers/cb_milestones_helper.rb
module CbMilestonesHelper
end

app/helpers/cb_objects_helper.rb
module CbObjectsHelper
end

app/helpers/cb_offices_helper.rb
module CbOfficesHelper
end

app/helpers/cb_people_helper.rb
module CbPeopleHelper
end

app/helpers/quantic_helper.rb
module QuanticHelper
    def bootstrap_version
        "4.2.1"
    end 
end

app/views/cb_funds/_form.html.erb
<%= form_with(model: cb_fund, local: true) do |form| %>
  <% if cb_fund.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cb_fund.errors.count, "error") %> prohibited this cb_fund from being saved:</h2>

      <ul>
      <% cb_fund.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fund_id %>
    <%= form.text_field :fund_id %>
  </div>

  <div class="field">
    <%= form.label :object_id %>
    <%= form.text_field :object_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :funded_at %>
    <%= form.date_select :funded_at %>
  </div>

  <div class="field">
    <%= form.label :raised_amount %>
    <%= form.text_field :raised_amount %>
  </div>

  <div class="field">
    <%= form.label :raised_currency_code %>
    <%= form.text_field :raised_currency_code %>
  </div>

  <div class="field">
    <%= form.label :source_url %>
    <%= form.text_field :source_url %>
  </div>

  <div class="field">
    <%= form.label :source_description %>
    <%= form.text_field :source_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cb_funds/edit.html.erb
<h1>Editing Cb Fund</h1>

<%= render 'form', cb_fund: @cb_fund %>

<%= link_to 'Show', @cb_fund %> |
<%= link_to 'Back', cb_funds_path %>

app/views/cb_funds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cb Funds</h1>

<table>
  <thead>
    <tr>
      <th>Fund</th>
      <th>Object</th>
      <th>Name</th>
      <th>Funded at</th>
      <th>Raised amount</th>
      <th>Raised currency code</th>
      <th>Source url</th>
      <th>Source description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cb_funds.each do |cb_fund| %>
      <tr>
        <td><%= cb_fund.fund %></td>
        <td><%= cb_fund.object %></td>
        <td><%= cb_fund.name %></td>
        <td><%= cb_fund.funded_at %></td>
        <td><%= cb_fund.raised_amount %></td>
        <td><%= cb_fund.raised_currency_code %></td>
        <td><%= cb_fund.source_url %></td>
        <td><%= cb_fund.source_description %></td>
        <td><%= link_to 'Show', cb_fund %></td>
        <td><%= link_to 'Edit', edit_cb_fund_path(cb_fund) %></td>
        <td><%= link_to 'Destroy', cb_fund, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cb Fund', new_cb_fund_path %>

app/views/cb_funds/new.html.erb
<h1>New Cb Fund</h1>

<%= render 'form', cb_fund: @cb_fund %>

<%= link_to 'Back', cb_funds_path %>

app/views/cb_funds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fund:</strong>
  <%= @cb_fund.fund %>
</p>

<p>
  <strong>Object:</strong>
  <%= @cb_fund.object %>
</p>

<p>
  <strong>Name:</strong>
  <%= @cb_fund.name %>
</p>

<p>
  <strong>Funded at:</strong>
  <%= @cb_fund.funded_at %>
</p>

<p>
  <strong>Raised amount:</strong>
  <%= @cb_fund.raised_amount %>
</p>

<p>
  <strong>Raised currency code:</strong>
  <%= @cb_fund.raised_currency_code %>
</p>

<p>
  <strong>Source url:</strong>
  <%= @cb_fund.source_url %>
</p>

<p>
  <strong>Source description:</strong>
  <%= @cb_fund.source_description %>
</p>

<%= link_to 'Edit', edit_cb_fund_path(@cb_fund) %> |
<%= link_to 'Back', cb_funds_path %>