config/routes.rb
Rails.application.routes.draw do

  resources :cb_relationships
  resources :cb_people
  resources :cb_offices
  resources :cb_objects
  resources :cb_milestones
  resources :cb_ipos
  resources :cb_investments
  resources :cb_funds
  resources :cb_funding_rounds
  resources :cb_degrees
  resources :cb_acquisitions
  root to: 'quantic#index'
  get 'quantic/about'

  devise_for :users

  authenticated :user do
    get 'quantic/browse' => 'cb_objects#index'
    get 'quantic/search' => 'cb_objects#search'
  end
  
  

end

app/models/cb_acquisition.rb
class CbAcquisition < ApplicationRecord
  belongs_to :acquisition
  belongs_to :acquiring_object
  belongs_to :acquired_object
end

app/models/cb_degree.rb
class CbDegree < ApplicationRecord
  belongs_to :object
end

app/models/cb_fund.rb
class CbFund < ApplicationRecord
  belongs_to :fund
  belongs_to :object
end

app/models/cb_funding_round.rb
class CbFundingRound < ApplicationRecord
  belongs_to :funding_round
  belongs_to :object
end

app/models/cb_investment.rb
class CbInvestment < ApplicationRecord
  belongs_to :funding_round
  belongs_to :funded_object
  belongs_to :investor_object
end

app/models/cb_ipo.rb
class CbIpo < ApplicationRecord
  belongs_to :ipo
  belongs_to :object
end

app/models/cb_milestone.rb
class CbMilestone < ApplicationRecord
  belongs_to :object
end

app/models/cb_object.rb
class CbObject < ActiveRecord::Base
#include Elasticsearch::Model
#include Elasticsearch::Model::CallBacks
  belongs_to :entity
  belongs_to :parent

  def self.search(search)
	  if search
		  name = name.find_by(name: search)
		if cb_object
			self.where(cb_objects_id: cb_object)
		else
		 cb_object.all
	 	end
       	else
	cb_object.all
	end
  	end

  def next
    self.class.where("id > ?", id).first
  end

  def previous
    self.class.where("id < ?", id).last
  end

end

app/models/cb_office.rb
class CbOffice < ApplicationRecord
  belongs_to :object
  belongs_to :office
end

app/models/cb_person.rb
class CbPerson < ApplicationRecord
  belongs_to :object
end

app/models/cb_relationship.rb
class CbRelationship < ApplicationRecord
  belongs_to :relationship
  belongs_to :person_object
  belongs_to :relationship_object
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cb_degrees_controller.rb
class CbDegreesController < ApplicationController
  before_action :set_cb_degree, only: [:show, :edit, :update, :destroy]

  # GET /cb_degrees
  # GET /cb_degrees.json
  def index
    @cb_degrees = CbDegree.all
  end

  # GET /cb_degrees/1
  # GET /cb_degrees/1.json
  def show
  end

  # GET /cb_degrees/new
  def new
    @cb_degree = CbDegree.new
  end

  # GET /cb_degrees/1/edit
  def edit
  end

  # POST /cb_degrees
  # POST /cb_degrees.json
  def create
    @cb_degree = CbDegree.new(cb_degree_params)

    respond_to do |format|
      if @cb_degree.save
        format.html { redirect_to @cb_degree, notice: 'Cb degree was successfully created.' }
        format.json { render :show, status: :created, location: @cb_degree }
      else
        format.html { render :new }
        format.json { render json: @cb_degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cb_degrees/1
  # PATCH/PUT /cb_degrees/1.json
  def update
    respond_to do |format|
      if @cb_degree.update(cb_degree_params)
        format.html { redirect_to @cb_degree, notice: 'Cb degree was successfully updated.' }
        format.json { render :show, status: :ok, location: @cb_degree }
      else
        format.html { render :edit }
        format.json { render json: @cb_degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cb_degrees/1
  # DELETE /cb_degrees/1.json
  def destroy
    @cb_degree.destroy
    respond_to do |format|
      format.html { redirect_to cb_degrees_url, notice: 'Cb degree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cb_degree
      @cb_degree = CbDegree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cb_degree_params
      params.require(:cb_degree).permit(:object_id, :degree_type, :subject, :institution, :graduated_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cb_degrees_helper.rb
module CbDegreesHelper
end

app/helpers/cb_funds_helper.rb
module CbFundsHelper
end

app/helpers/cb_investments_helper.rb
module CbInvestmentsHelper
end

app/helpers/cb_ipos_helper.rb
module CbIposHelper
end

app/helpers/cb_milestones_helper.rb
module CbMilestonesHelper
end

app/helpers/cb_objects_helper.rb
module CbObjectsHelper
end

app/helpers/cb_offices_helper.rb
module CbOfficesHelper
end

app/helpers/cb_people_helper.rb
module CbPeopleHelper
end

app/helpers/quantic_helper.rb
module QuanticHelper
    def bootstrap_version
        "4.2.1"
    end 
end

app/views/cb_degrees/_form.html.erb
<%= form_with(model: cb_degree, local: true) do |form| %>
  <% if cb_degree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cb_degree.errors.count, "error") %> prohibited this cb_degree from being saved:</h2>

      <ul>
      <% cb_degree.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :object_id %>
    <%= form.text_field :object_id %>
  </div>

  <div class="field">
    <%= form.label :degree_type %>
    <%= form.text_field :degree_type %>
  </div>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject %>
  </div>

  <div class="field">
    <%= form.label :institution %>
    <%= form.text_field :institution %>
  </div>

  <div class="field">
    <%= form.label :graduated_at %>
    <%= form.date_select :graduated_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cb_degrees/edit.html.erb
<h1>Editing Cb Degree</h1>

<%= render 'form', cb_degree: @cb_degree %>

<%= link_to 'Show', @cb_degree %> |
<%= link_to 'Back', cb_degrees_path %>

app/views/cb_degrees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cb Degrees</h1>

<table>
  <thead>
    <tr>
      <th>Object</th>
      <th>Degree type</th>
      <th>Subject</th>
      <th>Institution</th>
      <th>Graduated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cb_degrees.each do |cb_degree| %>
      <tr>
        <td><%= cb_degree.object %></td>
        <td><%= cb_degree.degree_type %></td>
        <td><%= cb_degree.subject %></td>
        <td><%= cb_degree.institution %></td>
        <td><%= cb_degree.graduated_at %></td>
        <td><%= link_to 'Show', cb_degree %></td>
        <td><%= link_to 'Edit', edit_cb_degree_path(cb_degree) %></td>
        <td><%= link_to 'Destroy', cb_degree, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cb Degree', new_cb_degree_path %>

app/views/cb_degrees/new.html.erb
<h1>New Cb Degree</h1>

<%= render 'form', cb_degree: @cb_degree %>

<%= link_to 'Back', cb_degrees_path %>

app/views/cb_degrees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Object:</strong>
  <%= @cb_degree.object %>
</p>

<p>
  <strong>Degree type:</strong>
  <%= @cb_degree.degree_type %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @cb_degree.subject %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @cb_degree.institution %>
</p>

<p>
  <strong>Graduated at:</strong>
  <%= @cb_degree.graduated_at %>
</p>

<%= link_to 'Edit', edit_cb_degree_path(@cb_degree) %> |
<%= link_to 'Back', cb_degrees_path %>